# Generated by Django 4.0.1 on 2022-06-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Tipo_mascota',
            fields=[
                ('id_tipo_mascota', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de mascota',
                'verbose_name_plural': 'Tipos de mascota',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=800)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('direccion_calle', models.CharField(max_length=100)),
                ('direccion_numero', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('enfermedad', models.IntegerField()),
                ('enfermedad_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('raza', models.CharField(blank=True, max_length=60, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('esterilizado', models.IntegerField()),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_mascota')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(check=models.Q(('rut__range', (1000000, 40000000))), name='check_usuario_rut'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(check=models.Q(('dv__in', '0123456789K')), name='check_usuario_dv'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 0)), name='check_usuario_edad'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 0)), name='check_mascota_edad'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(check=models.Q(('enfermedad__in', (0, 1))), name='check_mascota_enfermedad'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(check=models.Q(('sexo__in', 'HM')), name='check_mascota_sexo'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(check=models.Q(('esterilizado__in', (0, 1))), name='check_mascota_esterilizado'),
        ),
    ]
