# Generated by Django 4.0.1 on 2022-06-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=130, verbose_name='Descripcion del producto')),
                ('stock', models.PositiveIntegerField()),
                ('extra_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
