# Generated by Django 4.0.4 on 2022-06-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando pedido'), ('preparando', 'Preparando pedido'), ('enviando', 'Enviando pedido'), ('camino', 'Pedido en camino'), ('recibido', 'Su pedido ha llegado al destino')], default='procesando', max_length=200),
        ),
    ]
