# Generated by Django 4.0.4 on 2022-06-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suscripcion',
            field=models.BooleanField(default=False),
        ),
    ]
