# Generated by Django 4.0.4 on 2022-06-30 10:08

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_boleta_fecha_compra_boleta_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha_compra',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='check_boleta_total'),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.CheckConstraint(check=models.Q(('fecha_entrega__gte', django.db.models.expressions.F('fecha_compra'))), name='check_boleta_fecha'),
        ),
    ]
