# Generated by Django 4.0.4 on 2022-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_boleta_fecha_compra_alter_boleta_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
