# Generated by Django 4.0.4 on 2022-06-30 10:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boleta_fecha_despacho'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boleta',
            name='check_boleta_fecha',
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.CheckConstraint(check=models.Q(('fecha_despacho__gte', django.db.models.expressions.F('fecha_compra'))), name='check_boleta_fecha_despacho'),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.CheckConstraint(check=models.Q(('fecha_entrega__gte', django.db.models.expressions.F('fecha_despacho'))), name='check_boleta_fecha_entrega'),
        ),
    ]
